/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_content_delivery_bucket": "echocarbon2-20210308222932-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://echocarbon2-20210308222932-hostingbucket-dev.s3-website-us-west-2.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-west-2:0c80887d-3c90-41e2-a6ce-c37b78c842f6",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_YU6nuhndg",
    "aws_user_pools_web_client_id": "7g54lsdieaeoj7t32s2tbjdbpq",
    "oauth": {},
    "aws_bots": "enable",
    "aws_bots_config": [
        {
            "name": "BookTrip_dev",
            "alias": "$LATEST",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
